config/routes.rb
Rails.application.routes.draw do
  root 'users#index' 
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[index show update] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  # PUT and PATCH requests are used to update existing data
  put '/users/:id', to:  'users#update_img'

  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'
  
  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end 
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # associative links create two associations between Friendships and User
  # the columns ‘sent_to_id’ and ‘sent_by_id’ as foreign keys are linked 
  # with 'sent_to' and 'sent_by' due to assosiations 
  belongs_to :sent_to, class_name: 'User', foreign_key: 'sent_to_id'
  belongs_to :sent_by, class_name: 'User', foreign_key: 'sent_by_id'
  scope :friends, -> { where('status =?', true) }
  scope :not_friends, -> { where('status =?', false) }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include ApplicationHelper

  def create
    return if current_user.id == params[:user_id] # Disallow the ability to send yourself a friend request
    # Disallow the ability to send friend request more than once to same person
    return if friend_request_sent?(User.find(params[:user_id]))
    # Disallow the ability to send friend request to someone who already sent you one
    return if friend_request_received?(User.find(params[:user_id]))

    @user = User.find(params[:user_id])
    # Since this friendships controller create method is a nested route under the users resource 
    # the route created provides the parameter user_id for use within this function
    # current_user.friend_sent.build() creates a new record in the Friendship table 
    # supplying the value of sent_by_id as that of the current user using the friend_sent association 
    # between the User model and Friendship model
    @friendship = current_user.friend_sent.build(sent_to_id: params[:user_id])
    if @friendship.save
      flash[:success] = 'Friend Request Sent!'
      @notification = new_notification(@user, @current_user.id, 'friendRequest')
      @notification.save
    else
      flash[:danger] = 'Friend Request Failed!'
    end
    redirect_back(fallback_location: root_path)
  end

  # The accept_friend method updates the friendship record in the Friendship table 
  # setting the status of the record to true which we used to signify that the users are friends
  def accept_friend
    @friendship = Friendship.find_by(sent_by_id: params[:user_id], sent_to_id: current_user.id, status: false)
    return unless @friendship # return if no record is found

    @friendship.status = true
    if @friendship.save
      flash[:success] = 'Friend Request Accepted!'
      # Once the original record is updated and saved a duplicate record is created. 
      # This duplicate record will have the inverse value for sent_by_id and sent_to_id. 
      # This makes it easier to perform friending tasks and database checks to determine friends lists.
      # Upon accepting the friend request another friend request is made automatically. 
      @friendship2 = current_user.friend_sent.build(sent_to_id: params[:user_id], status: true)
      @friendship2.save
    else
      flash[:danger] = 'Friend Request could not be accepted!'
    end
    redirect_back(fallback_location: root_path)
  end

  # If a user declines a friend request the record is deleted out of the Friendship table
  def decline_friend
    @friendship = Friendship.find_by(sent_by_id: params[:user_id], sent_to_id: current_user.id, status: false)
    return unless @friendship # return if no record is found

    @friendship.destroy
    flash[:success] = 'Friend Request Declined!'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_decisionModal.html.erb
<!-- Modal >>
<div class="modal fade" id="decisionModal" tabindex="-1" role="dialog" aria-labelledby="decisionModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">   
      <div class="modal-body">
        <h5 class="modal-title" id="decisionModalLabel">Friend Request from <%= "#{object.full_name}" %></h5>
      </div>      
      <div class="modal-footer">
        <%= link_to accept_friend_user_friendships_path(object) do %>
          <button type="button" class="btn btn-accept text-white font-weight-bold"> <i class="fas fa-user-check"></i> Accept</button>
        <% end %>
        <%= link_to decline_friend_user_friendships_path(object) do %>
          <button type="button" class="btn btn-decline text-white font-weight-bold"><i class="fas fa-user-times"></i> Decline</button>
        <% end %>
      </div>
      
    </div>
  </div>  
</div>
<<  Modal -->

<!-- Modal -->
<div class="">
  <h5 class="" id="">Friend Request from <%= "#{object.full_name}" %></h5>
      </div>      
<div class="">
  <%= link_to accept_friend_user_friendships_path(object) do %>
    <button type="button" class="btn btn-accept text-black font-weight-bold"> <i class="fas fa-user-check"></i> Accept</button>
  <% end %>
  <%= link_to decline_friend_user_friendships_path(object) do %>
    <button type="button" class="btn btn-decline text-black font-weight-bold"><i class="fas fa-user-times"></i> Decline</button>
  <% end %>
</div>
 