config/routes.rb
Rails.application.routes.draw do
  root 'users#index' 
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[index show update] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  # PUT and PATCH requests are used to update existing data
  put '/users/:id', to:  'users#update_img'

  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'
  
  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end 
end

app/views/layouts/_flash.html.erb
<!-- scans through each of the key, value pairs of the flashes Hash -->

<% flash.each do |message_type, message| %>
<!-- creates a new div -->
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_header.html.erb
<header class="fixed-top navbar-dark bg-dark shadow">
  <div>
    <nav class="navbar navbar-expand-sm">
      <div class ="navbar-header"> 
        <%= link_to posts_path, class: "text-light" do %>
          <%=image_tag("user-secret-solid.svg", id: "logo", class: "navbar-branch")%>
          <span class="text-white font-weight-bold font-courgette size-24">Phizbook</span>
        <% end %>
      </div>
      <div class= "container mx-auto">
        <div class= "row mx-auto">
          <div class= "col-auto">
          <!--  links to the Posts index view -->
            <%= link_to posts_path, class: "text-light nav-link font-raleway" do%>
              <i class="fas fa-home fa-2x"></i> Timeline
            <%end%>
          </div>
          <div class= "col-auto">
            <!--  links to the Users index view -->
            <%= link_to users_path, class: "text-light nav-link font-raleway" do%>
              <i class="fas fa-users fa-2x"></i> Find Friends
            <%end%>
          </div>
        </div>
      </div>
 <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to saw_notice_path, :class => "text-white btn notice-btn-#{notification_seen}", 
             data: {toggle: 'modal', target: '#noticeModal'}, method: :get, remote: true do %>
             <% if notification_seen %>
              <i class="fas fa-bell-slash"></i>
             <% else %>
              <i class="fas fa-bell"></i>
             <% end %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a id= "navbarDropdown" class="nav-link dropdown-toggle font-raleway text-white" 
                href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account <b class="caret"></b>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <!--  links to the Users show view -->
              <%= link_to "My Profile", user_path(current_user), class: "dropdown-item font-raleway" %>
              <!--  links to a devise sessions controller destroy method -->
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item font-raleway", method: :delete %>
            </div>
          </li>
        <% end %>
      </ul> 
    </nav>    
  </div>  
</header>


<div class="">
  <% if user_signed_in? %>
  <!--  links to the Users show view -->
    <%= link_to "My Profile", user_path(current_user), class: "dropdown-item font-raleway text-success" %>
  <!--  links to a devise sessions controller destroy method -->
    <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item font-raleway text-warning", method: :delete %>
  <% end %>
</div>

<!-- allows a pop up to appear once clicked -->
<% if user_signed_in? %>
  <%= render 'shared/notifications', object: current_user.notifications%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phizlog</title>
    <%= favicon_link_tag asset_path('user-secret-solid-black.svg')%>
    <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Arima+Madurai:700|Courgette|Raleway:400,500&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>       
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <br>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>